--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bob/bob/wallpapers/45.jpg"

-- Special
background="#050611"
foreground="#cadce5"
cursor="#cadce5"

-- Colors
color0="#050611"
color1="#1766AC"
color2="#358CBA"
color3="#07B7DB"
color4="#23A0D4"
color5="#56AED8"
color6="#5DC3DC"
color7="#cadce5"
color8="#8d9aa0"
color9="#1766AC"
color10="#358CBA"
color11="#07B7DB"
color12="#23A0D4"
color13="#56AED8"
color14="#5DC3DC"
color15="#cadce5"
