# Shell variables
# Generated by 'wal'
wallpaper='/home/bob/bob/wallpapers/45.jpg'

# Special
background='#050611'
foreground='#cadce5'
cursor='#cadce5'

# Colors
color0='#050611'
color1='#1766AC'
color2='#358CBA'
color3='#07B7DB'
color4='#23A0D4'
color5='#56AED8'
color6='#5DC3DC'
color7='#cadce5'
color8='#8d9aa0'
color9='#1766AC'
color10='#358CBA'
color11='#07B7DB'
color12='#23A0D4'
color13='#56AED8'
color14='#5DC3DC'
color15='#cadce5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
